global:
  resolve_timeout: 1m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: karthickoncloud@gmail.com
  smtp_auth_username: karthickoncloud@gmail.com
  smtp_auth_password: password
  smtp_require_tls: true

templates:
  - /etc/alertmanager/template/*.tmpl

route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 1h
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: your-email2@gmail.com
        send_resolved: true
        require_tls: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - instance
