global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - rules.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node_exporter
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9100
