filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /hostfs/var/log/syslog
      - /hostfs/var/log/auth.log
      - /hostfs/var/log/messages
    fields:
      source_type: system
    fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
